###############################################################################
# SPECtools2000
#   Version 0.3
#   This makefile should NOT be changed other than to customize for a 
#   particular benchmark.  Users may overide variables by placing them
#   in the Makefile.spec file.  Or by using the "runspec" program to 
#   build the Makefile.spec file for them.
###############################################################################
#	BENCHMARK	-- standard definitions for this benchmark

NUMBER    = 181
NAME      = mcf
EXEBASE   = mcf
BENCHLANG = C
SOURCES   = mcf.c mcfutil.c readmin.c implicit.c pstart.c output.c \
	    treeup.c pbla.c pflowup.c psimplex.c pbeampp.c
NEED_MATH = yes

# Include standard template for this suite
#-include ../../../../Makefile.defaults
#-include ../../../Makefile.defaults
#-include ../../Makefile.defaults
#-include ../Makefile.defaults
all: 
	gcc -O3 $(SOURCES) -o mcf
	
clean:
	rm -f *~ *.o mcf

nomakefiles:
	@echo "*** Whoops!  I didn't find a Makefile.defaults file."
	@echo "*** Your distribution is probably corrupt."
	@echo
